CREATE TABLE wallets (
   id UUID   PRIMARY KEY,
   user_id UUID NOT NULL UNIQUE REFERENCES users(id),
   currency  VARCHAR(3) NOT NULL,
   version INTEGER NOT NULL DEFAULT 0,
   created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);